services:
  - type: web
    name: biathlon-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MYSQL_HOST
        sync: false
      - key: MYSQL_USER
        sync: false  
      - key: MYSQL_PASSWORD
        sync: false
      - key: MYSQL_DATABASE
        sync: false